# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪一个分支
branches:
  only:
  - source
# 缓存，能够节省集成的时间，这里我用了yarn，若是不用能够删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "wjwdive"
- git config --global user.email "wjwdive@163.com"
# 因为使用了yarn，因此须要下载，如不用yarn这两行能够删除
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
install:
# 不用yarn的话这里改为 npm i 便可
- yarn
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即以前在 travis 项目的环境变量里添加的
- git push --quiet --force https://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@github.com/wjwdive/wjwdive.github.io.git
  main
